<h1>New User</h1>
<form action="/users" method="post">
    <div>
        <label>
            Nickname
            <input type="text" name="user[nickname]" required>
        </label>
    </div>
    <div>
        <label>
            Email
            <input type="email" name="user[email]" required >
        </label>
    </div>
    <br>
    <div>
        <input type="submit" value="Submit">
    </div>

</form>